version: '3.8'

services:
  mariadb:
    image: mariadb:10.2
    container_name: my-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../../TMS_DB_mount/db_1:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: my-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
    ports:
      - "80:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge