version: '3.8'

services:
  mariadb:
    image: mariadb:10.2
    container_name: my-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../../TMS_DB_mount/db_1:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: my-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
    ports:
      - "80:80"
    networks:
      - my_network
  minio:
    image: quay.io/minio/minio:latest
    container_name: my-minio
    command: server --console-address ":9001"
    environment:
      MINIO_CONFIG_ENV_FILE: /etc/config.env
    volumes:
      - ../../TMS_FS_mount:/mnt/data
      - ./minio/config.env:/etc/config.env
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - my_network


networks:
  my_network:
    driver: bridge